/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
    Emmas
    Record: info
    ID, Name,Make,Model, (int)Year,Colour,Plate,License
 */
package emmas.car.lot;

import java.awt.Color;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emamera
 */
public class Homes extends javax.swing.JFrame {

    /**
     * Creates new form Homes
     */
    public DatabaseSevices dbs = new DatabaseSevices();
    javax.swing.JTable dataTable;
    int id;
    public Homes() {
        initComponents();
        dataTable = jTable1;
        this.setTitle("Emmas");
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/emmas/car/lot/icons8_snow_plow_25px.png")).getImage());
        dbs.View(this,jTable1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        removebtn = new javax.swing.JLabel();
        addbtn = new javax.swing.JLabel();
        update = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        removebtn.setBackground(new java.awt.Color(0, 51, 51));
        removebtn.setForeground(new java.awt.Color(153, 153, 153));
        removebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        removebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emmas/car/lot/icons/icons8_denied_25px_1.png"))); // NOI18N
        removebtn.setText("Remove");
        removebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removebtn.setOpaque(true);
        removebtn.setPreferredSize(new java.awt.Dimension(19, 14));
        removebtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                removebtnMouseMoved(evt);
            }
        });
        removebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removebtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                removebtnMouseExited(evt);
            }
        });
        getContentPane().add(removebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 100, 30));

        addbtn.setBackground(new java.awt.Color(0, 51, 51));
        addbtn.setForeground(new java.awt.Color(153, 153, 153));
        addbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emmas/car/lot/icons/icons8_add_user_group_man_man_25px.png"))); // NOI18N
        addbtn.setText("Add");
        addbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addbtn.setOpaque(true);
        addbtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                addbtnMouseMoved(evt);
            }
        });
        addbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addbtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addbtnMouseExited(evt);
            }
        });
        getContentPane().add(addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 100, 30));

        update.setBackground(new java.awt.Color(0, 51, 51));
        update.setForeground(new java.awt.Color(153, 153, 153));
        update.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emmas/car/lot/icons/icons8_update_user_25px.png"))); // NOI18N
        update.setText("Update");
        update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update.setOpaque(true);
        update.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                updateMouseMoved(evt);
            }
        });
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateMouseExited(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 100, 30));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name ", "Make", "Model", "Year", "Colour", "Plate no.", "Lincence no."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setDoubleBuffered(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 850, 400));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Select an Item to Delete");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 270, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emmas/car/lot/icons/icons8_refresh_25px.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, 50, 30));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 630, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbtnMouseClicked
        Add addForm = new Add();
        addForm.setVisible(true);
        addForm.jTextFields.setText("Homw");
    }//GEN-LAST:event_addbtnMouseClicked

    private void addbtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbtnMouseMoved
        // TODO add your handling code here:
       addbtn.setBackground(new Color(0,153,153));
       removebtn.setBackground(new Color(0,51,51));
       removebtn.setForeground(new Color(153,153,153));
       addbtn.setForeground(Color.white);
    }//GEN-LAST:event_addbtnMouseMoved

    private void removebtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removebtnMouseMoved
        // TODO add your handling code here:
       addbtn.setBackground(new Color(0,51,51));
       removebtn.setBackground(new Color(0,153,153));
       removebtn.setForeground(Color.white);
       addbtn.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_removebtnMouseMoved

    private void addbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbtnMouseExited
        // TODO add your handling code here:
       addbtn.setBackground(new Color(0,51,51));
       addbtn.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_addbtnMouseExited

    private void removebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removebtnMouseExited
        // TODO add your handling code here:
       removebtn.setBackground(new Color(0,51,51));
       removebtn.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_removebtnMouseExited

    private void updateMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseMoved
        // TODO add your handling code here:
       update.setBackground(new Color(0,153,153));
       update.setForeground(Color.white);
    }//GEN-LAST:event_updateMouseMoved

    private void updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseExited
        // TODO add your handling code here:
       update.setBackground(new Color(0,51,51));
       update.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_updateMouseExited

    private void removebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removebtnMouseClicked
        // TODO add your handling code here:
        remove rm = new remove();
        DefaultTableModel dft = (DefaultTableModel) jTable1.getModel();
       int selectIndex = jTable1.getSelectedRow();
        rm.jTextFields.setText((String) dft.getValueAt(selectIndex, 0));
        rm.setVisible(true);
    }//GEN-LAST:event_removebtnMouseClicked

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        // TODO add your handling code here:
        Update update = new Update();
        update.setVisible(true);
    }//GEN-LAST:event_updateMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
       DefaultTableModel dft = (DefaultTableModel) jTable1.getModel();
       int selectIndex = jTable1.getSelectedRow();
       id = Integer.parseInt((String) dft.getValueAt(selectIndex, 0));
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DatabaseSevices dbs = new DatabaseSevices();
        dbs.View(this,jTable1);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel removebtn;
    private javax.swing.JLabel update;
    // End of variables declaration//GEN-END:variables
}
