/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emmas.car.lot;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Emamera
 */
public class remove extends javax.swing.JFrame {

    /**
     * Creates new form Add
     */
    public DatabaseSevices dbs = new DatabaseSevices();
    public javax.swing.JTextField jTextFields;
    public remove() {
        initComponents();
        jTextFields = ID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JLabel();
        savebtn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Remove Data");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 20));

        ID.setText("ID");
        ID.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                IDMouseMoved(evt);
            }
        });
        ID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IDMouseExited(evt);
            }
        });
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 350, 30));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emmas/car/lot/icons/icons8_collaborator_male_25px.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 30, 30));

        cancelBtn.setBackground(new java.awt.Color(0, 153, 153));
        cancelBtn.setForeground(new java.awt.Color(240, 240, 240));
        cancelBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emmas/car/lot/icons/icons8_cancel_subscription_25px.png"))); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelBtn.setOpaque(true);
        cancelBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cancelBtnMouseMoved(evt);
            }
        });
        cancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelBtnMouseExited(evt);
            }
        });
        getContentPane().add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 90, 30));

        savebtn.setBackground(new java.awt.Color(0, 153, 153));
        savebtn.setForeground(new java.awt.Color(240, 240, 240));
        savebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        savebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emmas/car/lot/icons/icons8_save_as_25px.png"))); // NOI18N
        savebtn.setText("Remove");
        savebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        savebtn.setOpaque(true);
        savebtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                savebtnMouseMoved(evt);
            }
        });
        savebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                savebtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                savebtnMouseExited(evt);
            }
        });
        getContentPane().add(savebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 90, 30));

        jLabel2.setBackground(new java.awt.Color(0, 51, 51));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 2, 450, 200));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void IDMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IDMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_IDMouseMoved

    private void IDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IDMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_IDMouseExited

    private void cancelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseClicked
        // TODO add your handling code here                                     
        this.setVisible(false);
    }//GEN-LAST:event_cancelBtnMouseClicked

    private void savebtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savebtnMouseMoved
        // TODO add your handling code here:
        savebtn.setBackground(new Color(0,102,204));
    }//GEN-LAST:event_savebtnMouseMoved

    private void savebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savebtnMouseExited
        // TODO add your handling code here:[]
        savebtn.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_savebtnMouseExited

    private void cancelBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseMoved
        // TODO add your handling code here:
        cancelBtn.setBackground(new Color(0,102,204));
    }//GEN-LAST:event_cancelBtnMouseMoved

    private void cancelBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelBtnMouseEntered

    private void cancelBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseExited
        // TODO add your handling code here:
        cancelBtn.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_cancelBtnMouseExited

    private void savebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savebtnMouseClicked
        // TODO add your handling code here:
        if(ID.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Text is Empty");
        }else{
            int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to delete this item","Warning",JOptionPane.YES_NO_OPTION);
            if(dialogResult == JOptionPane.YES_OPTION){
                dbs.DeleteItem(this, Integer.parseInt(ID.getText()));
            }
            this.setVisible(false);
        }
    }//GEN-LAST:event_savebtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(remove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(remove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(remove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(remove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new remove().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JLabel cancelBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel savebtn;
    // End of variables declaration//GEN-END:variables
}
