/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emmas.car.lot;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Emamera
 */
public class Update extends javax.swing.JFrame {

    /**
     * Creates new form Add
     */
    DatabaseSevices services = new DatabaseSevices();
    public Update() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        model = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        make = new javax.swing.JTextField();
        year = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        savebtn = new javax.swing.JLabel();
        colour = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        plate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        license = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Id = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cancelBtn1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Update Data");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 20));

        model.setText("Model");
        model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelActionPerformed(evt);
            }
        });
        getContentPane().add(model, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 350, 30));

        name.setText("Name");
        name.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                nameMouseMoved(evt);
            }
        });
        name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nameMouseExited(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 350, 30));

        make.setText("Make");
        getContentPane().add(make, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 350, 30));

        year.setText("Year");
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });
        getContentPane().add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 350, 30));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emmas/car/lot/icons/icons8_tesla_model_x_25px.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 30, 30));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emmas/car/lot/icons/icons8_collaborator_male_25px.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 30, 30));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emmas/car/lot/icons/icons8_ice_maker_25px.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 30, 30));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emmas/car/lot/icons/icons8_15_25px.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 30, 30));

        savebtn.setBackground(new java.awt.Color(0, 153, 153));
        savebtn.setForeground(new java.awt.Color(240, 240, 240));
        savebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        savebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emmas/car/lot/icons/icons8_save_as_25px.png"))); // NOI18N
        savebtn.setText("Save");
        savebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        savebtn.setOpaque(true);
        savebtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                savebtnMouseMoved(evt);
            }
        });
        savebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                savebtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                savebtnMouseExited(evt);
            }
        });
        getContentPane().add(savebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 90, 30));

        colour.setText("Colour");
        colour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colourActionPerformed(evt);
            }
        });
        getContentPane().add(colour, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 350, 30));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emmas/car/lot/icons/icons8_swatch_25px.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 30, 30));

        plate.setText("Plate no.");
        plate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plateActionPerformed(evt);
            }
        });
        getContentPane().add(plate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 350, 30));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emmas/car/lot/icons/icons8_vbs_25px.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 30, 30));

        license.setText("License");
        license.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licenseActionPerformed(evt);
            }
        });
        getContentPane().add(license, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 350, 30));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emmas/car/lot/icons/icons8_car_insurance_25px.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 30, 30));

        Id.setText("ID");
        Id.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                IdMouseMoved(evt);
            }
        });
        Id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IdMouseExited(evt);
            }
        });
        getContentPane().add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 150, 30));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emmas/car/lot/icons/icons8_sort_by_modified_date_25px.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 30, 30));

        cancelBtn1.setBackground(new java.awt.Color(0, 153, 153));
        cancelBtn1.setForeground(new java.awt.Color(240, 240, 240));
        cancelBtn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emmas/car/lot/icons/icons8_cancel_subscription_25px.png"))); // NOI18N
        cancelBtn1.setText("Cancel");
        cancelBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelBtn1.setOpaque(true);
        cancelBtn1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cancelBtn1MouseMoved(evt);
            }
        });
        cancelBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelBtn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelBtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelBtn1MouseExited(evt);
            }
        });
        getContentPane().add(cancelBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, 90, 30));

        jLabel2.setBackground(new java.awt.Color(0, 51, 51));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 2, 450, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void modelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelActionPerformed

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearActionPerformed

    private void nameMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_nameMouseMoved

    private void nameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_nameMouseExited

    private void savebtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savebtnMouseMoved
        // TODO add your handling code here:
        savebtn.setBackground(new Color(0,102,204));
    }//GEN-LAST:event_savebtnMouseMoved

    private void savebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savebtnMouseExited
        // TODO add your handling code here:[]
        savebtn.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_savebtnMouseExited

    private void savebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savebtnMouseClicked
        // TODO add your handling code here:
        if(name.getText().isEmpty()||make.getText().isEmpty()||model.getText().isEmpty()||year.getText().isEmpty()||colour.getText().isEmpty()||plate.getText().isEmpty()||license.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Your Text are empty");
        }else{
            services.Update(this,Integer.parseInt(Id.getText()), name.getText().trim(), make.getText().trim(), model.getText().trim(), Integer.parseInt(year.getText().trim()), colour.getText(), plate.getText(), license.getText().trim());
            this.setVisible(false);
        }
    }//GEN-LAST:event_savebtnMouseClicked

    private void colourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colourActionPerformed

    private void plateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plateActionPerformed

    private void licenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_licenseActionPerformed

    private void IdMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IdMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_IdMouseMoved

    private void IdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IdMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_IdMouseExited

    private void cancelBtn1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtn1MouseMoved
        // TODO add your handling code here:
        cancelBtn1.setBackground(new Color(0,102,204));
    }//GEN-LAST:event_cancelBtn1MouseMoved

    private void cancelBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtn1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_cancelBtn1MouseClicked

    private void cancelBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtn1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelBtn1MouseEntered

    private void cancelBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtn1MouseExited
        // TODO add your handling code here:
        cancelBtn1.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_cancelBtn1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Id;
    private javax.swing.JLabel cancelBtn1;
    private javax.swing.JTextField colour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField license;
    private javax.swing.JTextField make;
    private javax.swing.JTextField model;
    private javax.swing.JTextField name;
    private javax.swing.JTextField plate;
    private javax.swing.JLabel savebtn;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
