/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
    Toyota
    Record:- vehicles
    ID, Model,Style, (int)Quntity, (int)Price, (int) Year
 */
package speco;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Speco
 */
public class CarsInfo extends javax.swing.JFrame {

    /**
     * Creates new form CarsInfo
     */
    Connection connector;
    PreparedStatement pres;
    ResultSet res;
    CardLayout cardLayout;
    DefaultTableModel tableItem;
    public CarsInfo() {
        initComponents();
        this.setTitle("Toyota");
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/speco/icons/icons8_toyota_25px.png")).getImage());
        toyotaCarsList();
        JLabel [] labels = {cars, remove, update,add};
        for(JLabel leb : labels){
            leb.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    
                }

                @Override
                public void mousePressed(MouseEvent e) {
                }

                @Override
                public void mouseReleased(MouseEvent e) {}

                @Override
                public void mouseEntered(MouseEvent e) {
                    leb.setForeground(new Color(68,10,103));
                    leb.setBackground(new Color(180,174,232));
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    leb.setBackground(new Color(68,10,103));
                    leb.setForeground(new Color(255,227,254));
                }
            });
        }
        cardLayout = (CardLayout) views.getLayout();
    }
    
    public final void toyotaCarsList(){
        try {
            int ammount;
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            connector = DriverManager.getConnection("jdbc:ucanaccess://Toyota.accdb");
            pres = connector.prepareStatement("select * from vehicles");
            res = pres.executeQuery();
            ResultSetMetaData resultSet = res.getMetaData();
            ammount = resultSet.getColumnCount();
            
            tableItem = (DefaultTableModel) jTable1.getModel();
            tableItem.setRowCount(0);
            
            while(res.next()){
                Vector vects = new Vector();
                for(int i = 1; i<= ammount; i++){
                    //ID, Model,Style, (int)Quntity, (int)Price, (int) Year
                    vects.add(res.getString("ID"));
                    vects.add(res.getString("Model"));
                    vects.add(res.getString("Style"));
                    vects.add(res.getInt("Quntity"));
                    vects.add(res.getInt("Price"));
                    vects.add(res.getInt("Year"));
                }
                tableItem.addRow(vects);
            }
            
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        cars = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        add = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        update = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        remove = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();
        views = new javax.swing.JPanel();
        carView = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        newItemView = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        marketView = new javax.swing.JPanel();
        searchView = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setBackground(new java.awt.Color(65, 10, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(150, 455));

        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/speco/icons/icons8_toyota_96px_2.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 96));
        jPanel2.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Toyota Vehicle Information");
        jPanel2.add(jLabel2);

        jPanel7.setOpaque(false);
        jPanel7.setPreferredSize(new java.awt.Dimension(150, 60));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel7);

        cars.setBackground(new java.awt.Color(68, 10, 103));
        cars.setForeground(new java.awt.Color(255, 229, 254));
        cars.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cars.setIcon(new javax.swing.ImageIcon(getClass().getResource("/speco/icons/icons8_car_25px_1.png"))); // NOI18N
        cars.setText("CARS");
        cars.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cars.setIconTextGap(30);
        cars.setInheritsPopupMenu(false);
        cars.setOpaque(true);
        cars.setPreferredSize(new java.awt.Dimension(150, 30));
        cars.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                carsMouseMoved(evt);
            }
        });
        cars.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carsMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carsMouseExited(evt);
            }
        });
        jPanel2.add(cars);

        jPanel4.setOpaque(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4);

        add.setBackground(new java.awt.Color(68, 10, 103));
        add.setForeground(new java.awt.Color(255, 229, 254));
        add.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/speco/icons/icons8_add_new_25px_1.png"))); // NOI18N
        add.setText("Add Car");
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.setIconTextGap(30);
        add.setInheritsPopupMenu(false);
        add.setOpaque(true);
        add.setPreferredSize(new java.awt.Dimension(150, 30));
        add.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                addMouseMoved(evt);
            }
        });
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        jPanel2.add(add);

        jPanel5.setOpaque(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5);

        update.setBackground(new java.awt.Color(68, 10, 103));
        update.setForeground(new java.awt.Color(255, 229, 254));
        update.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/speco/icons/icons8_update_left_rotation_25px.png"))); // NOI18N
        update.setText("Update");
        update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update.setIconTextGap(30);
        update.setInheritsPopupMenu(false);
        update.setOpaque(true);
        update.setPreferredSize(new java.awt.Dimension(150, 30));
        update.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                updateMouseMoved(evt);
            }
        });
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateMouseExited(evt);
            }
        });
        jPanel2.add(update);

        jPanel6.setOpaque(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6);

        remove.setBackground(new java.awt.Color(68, 10, 103));
        remove.setForeground(new java.awt.Color(255, 229, 254));
        remove.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/speco/icons/icons8_remove_25px_1.png"))); // NOI18N
        remove.setText("Remove");
        remove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        remove.setIconTextGap(30);
        remove.setInheritsPopupMenu(false);
        remove.setOpaque(true);
        remove.setPreferredSize(new java.awt.Dimension(150, 30));
        remove.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                removeMouseMoved(evt);
            }
        });
        remove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                removeMouseExited(evt);
            }
        });
        jPanel2.add(remove);

        jPanel8.setOpaque(false);
        jPanel8.setPreferredSize(new java.awt.Dimension(150, 70));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel8);

        logout.setForeground(new java.awt.Color(240, 240, 240));
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.setPreferredSize(new java.awt.Dimension(150, 14));
        jPanel2.add(logout);

        getContentPane().add(jPanel2);

        views.setLayout(new java.awt.CardLayout());

        carView.setBackground(new java.awt.Color(0, 153, 153));
        carView.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Model", "Body Style", "Quntity", "Price", "Model Year"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        carView.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 27, 780, 540));

        views.add(carView, "card4");

        newItemView.setBackground(new java.awt.Color(0, 153, 153));
        newItemView.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Model", "Price", "BodyStyle", "Product year"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
        }

        newItemView.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 77, 750, 440));

        jLabel3.setBackground(new java.awt.Color(0, 204, 0));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Update");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.setOpaque(true);
        newItemView.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 550, 130, 30));

        jLabel4.setBackground(new java.awt.Color(0, 102, 204));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Add New Car");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.setOpaque(true);
        newItemView.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, 130, 30));

        views.add(newItemView, "card3");

        marketView.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout marketViewLayout = new javax.swing.GroupLayout(marketView);
        marketView.setLayout(marketViewLayout);
        marketViewLayout.setHorizontalGroup(
            marketViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 865, Short.MAX_VALUE)
        );
        marketViewLayout.setVerticalGroup(
            marketViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
        );

        views.add(marketView, "card5");

        searchView.setBackground(new java.awt.Color(0, 153, 153));
        searchView.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Search");
        searchView.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 120, 40));

        jFormattedTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField1.setText("Search by");
        searchView.add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 300, 40));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Information");
        searchView.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 200, 20));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Information");
        searchView.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 170, -1));

        views.add(searchView, "card2");

        getContentPane().add(views);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void carsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carsMouseMoved
        // TODO add your handling code here:
        ImageIcon ii = new ImageIcon(getClass().getResource("/speco/icons/icons8_car_25px.png"));
        cars.setIcon(ii);
    }//GEN-LAST:event_carsMouseMoved

    private void carsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carsMouseExited
        // TODO add your handling code here:
        ImageIcon ii = new ImageIcon(getClass().getResource("/speco/icons/icons8_car_25px_1.png"));
        cars.setIcon(ii);
    }//GEN-LAST:event_carsMouseExited

    private void updateMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseMoved
        // TODO add your handling code here:
        ImageIcon ii = new ImageIcon(getClass().getResource("/speco/icons/icons8_update_25px.png"));
        update.setIcon(ii);
    }//GEN-LAST:event_updateMouseMoved

    private void updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseExited
        // TODO add your handling code here:
        ImageIcon ii = new ImageIcon(getClass().getResource("/speco/icons/icons8_update_left_rotation_25px.png"));
        update.setIcon(ii);
    }//GEN-LAST:event_updateMouseExited

    private void removeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeMouseMoved
        // TODO add your handling code here:
        ImageIcon ii = new ImageIcon(getClass().getResource("/speco/icons/icons8_remove_25px_2.png"));
        remove.setIcon(ii);
    }//GEN-LAST:event_removeMouseMoved

    private void removeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeMouseExited
        // TODO add your handling code here:
        ImageIcon ii = new ImageIcon(getClass().getResource("/speco/icons/icons8_remove_25px_1.png"));
        remove.setIcon(ii);
    }//GEN-LAST:event_removeMouseExited

    private void carsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carsMouseClicked
        // TODO add your handling code here:
        toyotaCarsList();
        cardLayout.show(views, "card4");
    }//GEN-LAST:event_carsMouseClicked

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        // TODO add your handling code here:String Id,String Model, String Style, String Quntity, String Price, String Year
        tableItem = (DefaultTableModel) jTable1.getModel();
        int selectIndex = jTable1.getSelectedRow();
        Update upd= new Update(tableItem.getValueAt(selectIndex, 0).toString(),tableItem.getValueAt(selectIndex, 1).toString(),tableItem.getValueAt(selectIndex, 2).toString(),tableItem.getValueAt(selectIndex, 3).toString(),tableItem.getValueAt(selectIndex, 4).toString(),tableItem.getValueAt(selectIndex, 5).toString());
        upd.setVisible(true);
    }//GEN-LAST:event_updateMouseClicked

    private void removeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeMouseClicked
        // TODO add your handling code here:
        Remove rem = new Remove();
        rem.setVisible(true);
    }//GEN-LAST:event_removeMouseClicked

    private void addMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseMoved
        // TODO add your handling code here:
        ImageIcon ii = new ImageIcon(getClass().getResource("/speco/icons/icons8_add_new_25px.png"));
        add.setIcon(ii);
    }//GEN-LAST:event_addMouseMoved

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        // TODO add your handling code here:
        addToyota add = new addToyota();
        add.setVisible(true);
    }//GEN-LAST:event_addMouseClicked

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        // TODO add your handling code here:
        ImageIcon ii = new ImageIcon(getClass().getResource("/speco/icons/icons8_add_new_25px_1.png"));
        add.setIcon(ii);
    }//GEN-LAST:event_addMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarsInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarsInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarsInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarsInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarsInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add;
    private javax.swing.JPanel carView;
    private javax.swing.JLabel cars;
    private javax.swing.JButton jButton2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel logout;
    private javax.swing.JPanel marketView;
    private javax.swing.JPanel newItemView;
    private javax.swing.JLabel remove;
    private javax.swing.JPanel searchView;
    private javax.swing.JLabel update;
    private javax.swing.JPanel views;
    // End of variables declaration//GEN-END:variables
}
